export const LOGIN = 'LOGIN'
export const REFRESH_JWT_TOKEN = 'REFRESH_JWT_TOKEN'
export const SEARCH = 'SEARCH'
export const DEVICES = 'DEVICES'
export const DEVICE_GROUPS = 'DEVICE_GROUPS'
// TODO remove
export const DEVICE_GROUPS_BY_COMPANY_ID = 'DEVICE_GROUPS_BY_COMPANY_ID'
export const DEVICE_ALL = 'DEVICE_ALL'
export const COMPANIES = 'COMPANIES'
export const TYPES_ICONS = 'TYPES_ICONS'
export const FOUND_DEVICES_NUMBER = 'FOUND_DEVICES_NUMBER'
export const DEVICESPAGED = 'DEVICESPAGED'
export const SAVE_TAG = 'SAVE_TAG'
export const MOVE_DEVICE_TO_FAVORITE = 'MOVE_DEVICE_TO_FAVORITE'
export const CHANGE_DEVICE = 'CHANGE_DEVICE'
export const DEVICE_TYPES = 'DEVICE_TYPES'
export const GET_FAV_DEVICES = 'GET_FAV_DEVICES'

// CHARTS
export const CHARTS_INFO = 'CHARTS_INFO'
export const ALL_CHARTS_INFO = 'ALL_CHARTS_INFO'
export const DASHBOARD_STATIC = 'DASHBOARD_STATIC'

// TICKETS
export const GET_TICKETS = 'GET_TICKETS'
export const NEW_TICKET = 'NEW_TICKET'
export const GET_STATIC = 'GET_STATIC'
export const GET_TICKET_STATUSES = 'GET_TICKET_STATUSES'
export const GET_TICKETS_PAGE = 'GET_TICKETS_PAGE'
export const GET_DETAILS = 'GET_DETAILS'
export const GET_COMMENTS = 'GET_COMMENTS'
export const ADD_COMMENT = 'ADD_COMMENT'

// NOTIFICATIONS
export const GET_NOTIFICATIONS = 'GET_NOTIFICATIONS'

// METRICS
export const GET_METRICS = 'GET_METRICS'
export const GET_MONITORING_INFO = 'GET_MONITORING_INFO'
export const TOGGLE_FAVORITE = 'TOGGLE_FAVORITE'
export const GET_METRICS_SETTINGS = 'GET_METRICS_SETTINGS'
export const SAVE_METRICS_SETTINGS = 'SAVE_METRICS_SETTINGS'

// SEARCH
export const GET_SAVED_SEARCH_STRINGS = 'GET_SAVED_SEARCH_STRINGS'
export const SAVE_SEARCH_REQUEST = 'SAVE_SEARCH_REQUEST'

// REPORT
export const CREATE_REPORT = 'CREATE_REPORT'
