export const SPECS = 'SPECS'
export const TYPES = 'TYPES'
export const LANGS = 'LANGS'
export const COUNTRIES = 'COUNTRIES'
export const CITIES = 'CITIES'
export const ARTICLES = 'ARTICLES'
export const NEWS = 'NEWS'
export const SCHOOL = 'SCHOOL'
